### ISSUE TITLE
Setup commitlint

### ISSUE THREAD

**Issue by fersilva16** [woovibr/codemods#8]
[Commitlint's setup guide](https://commitlint.js.org/#/guides-local-setup)

- Should we use [commitizen](https://github.com/commitizen/cz-cli)?
- We'll be using a customized config? Or the [default one](https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional)?

**Comment by noghartt** [comment]
> Should we use commitizen?

I think that is unnecessary to use `commitizen` for now, it's a middleware step that can add more complexity. We can add a `CONTRIBUTE.md` file that explains the rules behind a commit and a `pre-commit` with commitlint that validate if it's in agreement. 

> We'll be using a customized config? Or the default one?

For now, we can use the default one, because it's easier to integrate with [standard-version](https://github.com/conventional-changelog/standard-version), etc. If necessary, we create a customized config. What do you think about it?

**Comment by fersilva16** [comment]
I agree with not using `commitizen`, and I like the idea of a `CONTRIBUTE.md` [as the angular does](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit).

And, yeah, we can use the default config, but I don't know if Entria has its Commitlint config or some other preferred config.

**Comment by sibelius** [comment]
We use commitLint, it helps to generate the changelogs

**Comment by Tsugami** [comment]
also to use commitlint with github action https://github.com/wagoid/commitlint-github-action
